name: athena
description: LMS

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Bruno
      fonts:
        - asset: assets/fonts/Bruno/BrunoAceSC-Regular.ttf

    - family: Motiva
      fonts:
        - asset: assets/fonts/Motiva/MotivaSansTest-Medium.otf